/*****************************************************************
 *
 * HwTaskInfo.cpp
 *
 * Shanghai Share-E tech. Co., LTD.
 *
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!! Do not edit this file. !!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 *
 * An auto-generated file, any modification will be ignored.
 *
 *****************************************************************/

#include "rtx_inc.h"
#include "HwSimTaskSupport.h"
#include "HwDataItem.h"


#ifdef __cplusplus
extern "C"
{
#endif

TASK_INFO g_TaskInfo =
{
	"ZhengJiCeShi", 0X6BE2543E3240234, 2500
};


extern const hw_uint16 g_SampleRates[] =
{
	1,
};
extern const hw_uint16 g_usSampleRateNum=1;


extern const USER_PORT g_Parameters[] =
{
	/* Name, Addr, BaseType, Width, Size, SampleRate, Path */
	{"测试项目", &g_ulTestCaseNo, 8, 1, 4, 0, "/"},
	{"输入频率", &g_dFreq, 0, 1, 8, 0, "/"},
	{"开关量DO", &DI_DO, 11, 1, 1, 0, "/开关量输入"},
	{"IMUTickFlag", &g_IMUTickFlag, 4, 1, 1, 0, "/IMU惯组"},
	{"报表第几次", &g_RunTimes, 4, 1, 1, 0, "/"},
	{"", 0, 0, 0, 0, 0, ""}
};
extern const hw_uint32 g_ulParameterNum=5;


extern const USER_PORT g_Variables[] =
{
	/* Name, Addr, BaseType, Width, Size, SampleRate, Path */
	{"当前子项目状态", &lFlag, 8, 1, 4, 0, "/"},
	{"27VA", &ADValue[0][AD0::DY27电源27V2输出电压监视], 0, 1, 8, 0, "/"},
	{"27VB", &ADValue[0][AD0::DY27电源27V3输出电压监视], 0, 1, 8, 0, "/"},
	{"60VC", &ADValue[0][AD0::XGLDY小功率60V电源输出电压监视], 0, 1, 8, 0, "/"},
	{"ReadValue", g_ReadValue, 0, 9, 72, 0, "/电源遥测"},
	{"惯测+15V遥测", &ADValue[0][AD0::GCZ15惯测正15V遥测], 0, 1, 8, 0, "/电源遥测"},
	{"惯测-15V遥测", &ADValue[0][AD0::GCF15惯测负15V遥测], 0, 1, 8, 0, "/电源遥测"},
	{"惯测+5V遥测", &ADValue[0][AD0::GCZ5惯测正5V遥测], 0, 1, 8, 0, "/电源遥测"},
	{"惯测-5V遥测", &ADValue[0][AD0::GCF5惯测负5V遥测], 0, 1, 8, 0, "/电源遥测"},
	{"主5V遥测", &ADValue[0][AD0::Z5VYC主5V遥测], 0, 1, 8, 0, "/电源遥测"},
	{"+15V遥测", &ADValue[0][AD0::Z15VYC正15V遥测], 0, 1, 8, 0, "/电源遥测"},
	{"-15V遥测", &ADValue[0][AD0::F15VYC负15V遥测], 0, 1, 8, 0, "/电源遥测"},
	{"电气控制+5V1遥测", &ADValue[0][AD0::DQKZ电气控制正5V1遥测], 0, 1, 8, 0, "/电源遥测"},
	{"电气控制+5V2遥测", &ADValue[0][AD0::DQKZ电气控制正5V2遥测], 0, 1, 8, 0, "/电源遥测"},
	{"RAM状态", g_FlagRAM, 8, 2, 8, 0, "/FLASH_RAM"},
	{"RAM失败地址", g_RAMAdress, 8, 2, 8, 0, "/FLASH_RAM"},
	{"FLASH块数", g_FlashNum, 8, 4, 16, 0, "/FLASH_RAM"},
	{"FLASH擦除成功", g_FlashClear, 8, 4, 16, 0, "/FLASH_RAM"},
	{"FLASH写入成功", g_FlashWrite, 8, 4, 16, 0, "/FLASH_RAM"},
	{"FLASH写入失败地址", g_FailAdress, 8, 4, 16, 0, "/FLASH_RAM"},
	{"报表FLASH", &g_FLASH, 4, 1, 1, 0, "/FLASH_RAM"},
	{"报表FLASHClose", &g_FLASHClose, 4, 1, 1, 0, "/FLASH_RAM"},
	{"报表SRAM", &g_SRAM, 4, 1, 1, 0, "/FLASH_RAM"},
	{"KO7上电时间", &g_TimeKO7, 0, 1, 8, 0, "/上电时间"},
	{"开机时间", &g_TimeTurnOn, 0, 1, 8, 0, "/上电时间"},
	{"IMU启动电流", g_IMUPowerStart, 0, 3, 24, 0, "/IMU惯组"},
	{"IMU稳定电流", g_IMUPowerRunState, 0, 3, 24, 0, "/IMU惯组"},
	{"IMUTickFlag0", &g_IMUTickFlag0, 4, 1, 1, 0, "/IMU惯组"},
	{"IMUTickBegin", &g_IMUTickBegin, 8, 1, 4, 0, "/IMU惯组"},
	{"IMUTickEnd", &g_IMUTickEnd, 8, 1, 4, 0, "/IMU惯组"},
	{"IMU_CNT", &g_IMUCount, 6, 1, 2, 0, "/IMU惯组"},
	{"接收帧数", &g_IMUCountRecv, 8, 1, 4, 0, "/IMU惯组"},
	{"丢失帧数", &g_IMUCountLoss, 8, 1, 4, 0, "/IMU惯组"},
	{"X轴角增量", &g_YTH.m_fdWx, 1, 1, 4, 0, "/IMU惯组"},
	{"Y轴角增量", &g_YTH.m_fdWy, 1, 1, 4, 0, "/IMU惯组"},
	{"Z轴角增量", &g_YTH.m_fdWz, 1, 1, 4, 0, "/IMU惯组"},
	{"X轴速度增量", &g_YTH.m_fdVx, 1, 1, 4, 0, "/IMU惯组"},
	{"Y轴速度增量", &g_YTH.m_fdVy, 1, 1, 4, 0, "/IMU惯组"},
	{"Z轴速度增量", &g_YTH.m_fdVz, 1, 1, 4, 0, "/IMU惯组"},
	{"X轴角速度", &g_YTH.m_fWx, 1, 1, 4, 0, "/IMU惯组"},
	{"Y轴角速度", &g_YTH.m_fWy, 1, 1, 4, 0, "/IMU惯组"},
	{"Z轴角速度", &g_YTH.m_fWz, 1, 1, 4, 0, "/IMU惯组"},
	{"X轴加速度", &g_YTH.m_fNx, 1, 1, 4, 0, "/IMU惯组"},
	{"Y轴加速度", &g_YTH.m_fNy, 1, 1, 4, 0, "/IMU惯组"},
	{"Z轴加速度", &g_YTH.m_fNz, 1, 1, 4, 0, "/IMU惯组"},
	{"惯组内温度", &g_YTH.m_fTemperature, 1, 1, 4, 0, "/IMU惯组"},
	{"X陀螺", &g_YTH.m_ucStatus_XTuoLuo, 4, 1, 1, 0, "/IMU惯组"},
	{"Y陀螺", &g_YTH.m_ucStatus_YTuoLuo, 4, 1, 1, 0, "/IMU惯组"},
	{"Z陀螺", &g_YTH.m_ucStatus_ZTuoLuo, 4, 1, 1, 0, "/IMU惯组"},
	{"X加表", &g_YTH.m_ucStatus_XJiaBiao, 4, 1, 1, 0, "/IMU惯组"},
	{"Y加表", &g_YTH.m_ucStatus_YJiaBiao, 4, 1, 1, 0, "/IMU惯组"},
	{"Z加表", &g_YTH.m_ucStatus_ZJiaBiao, 4, 1, 1, 0, "/IMU惯组"},
	{"工作温度检查", &g_YTH.m_ucStatus_Temperature, 4, 1, 1, 0, "/IMU惯组"},
	{"加载参数检查", &g_YTH.m_ucStatus_ParamCheck, 4, 1, 1, 0, "/IMU惯组"},
	{"DA输入值", &dDAInputValue, 1, 1, 4, 0, "/DA转换精度"},
	{"AD采集值", g_DAValue, 0, 80, 640, 0, "/DA转换精度"},
	{"舵指令U1遥测", &ADValue[1][AD1::DZL舵指令U1遥测], 0, 1, 8, 0, "/DA转换精度"},
	{"舵指令U2遥测", &ADValue[1][AD1::DZL舵指令U2遥测], 0, 1, 8, 0, "/DA转换精度"},
	{"舵指令U3遥测", &ADValue[1][AD1::DZL舵指令U3遥测], 0, 1, 8, 0, "/DA转换精度"},
	{"舵指令U4遥测", &ADValue[1][AD1::DZL舵指令U4遥测], 0, 1, 8, 0, "/DA转换精度"},
	{"舵指令U1(采集)", &ADValue[1][AD1::DZL舵指令U1], 0, 1, 8, 0, "/DA转换精度"},
	{"舵指令U2(采集)", &ADValue[1][AD1::DZL舵指令U2], 0, 1, 8, 0, "/DA转换精度"},
	{"舵指令U3(采集)", &ADValue[1][AD1::DZL舵指令U3], 0, 1, 8, 0, "/DA转换精度"},
	{"舵指令U4(采集)", &ADValue[1][AD1::DZL舵指令U4], 0, 1, 8, 0, "/DA转换精度"},
	{"串口错误计数", &g_Count_Wrong, 8, 1, 4, 0, "/串口测试"},
	{"串口发送计数", &g_Count, 8, 1, 4, 0, "/串口测试"},
	{"串口接收计数", &g_Count_Recv, 8, 1, 4, 0, "/串口测试"},
	{"串口错误率", &g_COMErrorRate, 0, 1, 8, 0, "/串口测试"},
	{"寄存器状态", bTimerState, 11, 5, 5, 0, "/CPU和寄存器"},
	{"寄存器回帧2", &bRegisterWrong, 11, 1, 1, 0, "/CPU和寄存器"},
	{"CPU_ID", &CPU_ID, 8, 1, 4, 0, "/建立连接"},
	{"CPU_Rev_ID", &CPU_Rev_ID, 8, 1, 4, 0, "/建立连接"},
	{"KI3A_0", &DI_KI[0][2], 11, 1, 1, 0, "/开关量"},
	{"KI3B_0", &DI_KI[0][7], 11, 1, 1, 0, "/开关量"},
	{"KI4_0", &DI_KI[0][3], 11, 1, 1, 0, "/开关量"},
	{"KI5_0", &DI_KI[0][4], 11, 1, 1, 0, "/开关量"},
	{"KI6_0", &DI_KI[0][5], 11, 1, 1, 0, "/开关量"},
	{"KI7_0", &DI_KI[0][6], 11, 1, 1, 0, "/开关量"},
	{"DDK11_0", &DI_KI[0][0], 11, 1, 1, 0, "/开关量"},
	{"DDK12_0", &DI_KI[0][1], 11, 1, 1, 0, "/开关量"},
	{"DI_DDK2_YC_0", &DI_DDK2_YC[0], 11, 1, 1, 0, "/开关量"},
	{"DI_DDK2_JC_0", &DI_DDK2_JC[0], 0, 1, 8, 0, "/开关量"},
	{"DI_DDK11_YC_0", &DI_DDK11_YC[0], 0, 1, 8, 0, "/开关量"},
	{"DI_DDK12_YC_0", &DI_DDK12_YC[0], 0, 1, 8, 0, "/开关量"},
	{"DI_KO7_0", &DI_KO7[0], 0, 1, 8, 0, "/开关量"},
	{"KI3A_1", &DI_KI[1][2], 11, 1, 1, 0, "/开关量"},
	{"KI3B_1", &DI_KI[1][7], 11, 1, 1, 0, "/开关量"},
	{"KI4_1", &DI_KI[1][3], 11, 1, 1, 0, "/开关量"},
	{"KI5_1", &DI_KI[1][4], 11, 1, 1, 0, "/开关量"},
	{"KI6_1", &DI_KI[1][5], 11, 1, 1, 0, "/开关量"},
	{"KI7_1", &DI_KI[1][6], 11, 1, 1, 0, "/开关量"},
	{"DDK11_1", &DI_KI[1][0], 11, 1, 1, 0, "/开关量"},
	{"DDK12_1", &DI_KI[1][1], 11, 1, 1, 0, "/开关量"},
	{"DI_DDK2_YC_1", &DI_DDK2_YC[1], 11, 1, 1, 0, "/开关量"},
	{"DI_DDK2_JC_1", &DI_DDK2_JC[1], 0, 1, 8, 0, "/开关量"},
	{"DI_DDK11_YC_1", &DI_DDK11_YC[1], 0, 1, 8, 0, "/开关量"},
	{"DI_DDK12_YC_1", &DI_DDK12_YC[1], 0, 1, 8, 0, "/开关量"},
	{"DI_KO7_1", &DI_KO7[1], 0, 1, 8, 0, "/开关量"},
	{"激活好", &ADValue[1][AD1::JHH激活好], 0, 1, 8, 0, "/激活好"},
	{"27VA_up", &g_27VA_up, 0, 1, 8, 0, "/激活好"},
	{"27VA_Down", &g_27VA_Down, 0, 1, 8, 0, "/激活好"},
	{"27VB_up", &g_27VB_up, 0, 1, 8, 0, "/激活好"},
	{"27VB_Down", &g_27VB_Down, 0, 1, 8, 0, "/激活好"},
	{"60VC_up", &g_60VC_up, 0, 1, 8, 0, "/激活好"},
	{"60VC_Down", &g_60VC_Down, 0, 1, 8, 0, "/激活好"},
	{"输出电流", &g_JHH_ValueA, 0, 1, 8, 0, "/激活好"},
	{"激活好+", &g_JHH_Value1, 0, 1, 8, 0, "/激活好"},
	{"激活好-", &g_JHH_Value2, 0, 1, 8, 0, "/激活好"},
	{"接地状态", &g_DDK2_GND, 0, 1, 8, 0, "/DDK2"},
	{"悬空状态", &g_DDK2_XuanKong, 0, 1, 8, 0, "/DDK2"},
	{"KO7", &ADValue[1][AD1::KO7], 0, 1, 8, 0, "/AD1"},
	{"", 0, 0, 0, 0, 0, ""}
};
extern const hw_uint32 g_ulVariableNum=111;


extern const USER_PORT g_InputPorts[] =
{
	/* Name, Addr, BaseType, Width, Size, SampleRate, Path */
	{"", 0, 0, 0, 0, 0, ""}
};
extern const hw_uint32 g_ulInputPortNum=0;


extern const USER_PORT g_OutputPorts[] =
{
	/* Name, Addr, BaseType, Width, Size, SampleRate, Path */
	{"", 0, 0, 0, 0, 0, ""}
};
extern const hw_uint32 g_ulOutputPortNum=0;


#ifdef __cplusplus
}
#endif

